import type { EvidenceItem, Report } from '../types'
import { formatDate, formatDateTime } from './format'
import { linkedEvidenceForFinding } from './evidence'

function inline(value: string): string {
  return value.replace(/\s+/g, ' ').trim()
}

export function reportToMarkdown(report: Report, evidenceItems: EvidenceItem[]): string {
  const lines = [`# ${report.title || 'Untitled Report'}`, '']
  if (report.scope) lines.push(`**Scope:** ${report.scope}`, '')
  lines.push('## Summary', '', report.summary || '_No summary._', '', '## Findings', '')
  if (report.findings.length === 0) lines.push('_No findings recorded._')

  report.findings.forEach((finding, index) => {
    lines.push(`### ${index + 1}. [${finding.severity.toUpperCase()}] ${finding.title || 'Untitled finding'}`)
    lines.push(`- **Impact:** ${finding.impact || '—'}`)
    lines.push(`- **Remediation:** ${finding.remediation || '—'}`)
    if (finding.evidence) lines.push(`- **Evidence note:** ${inline(finding.evidence)}`)

    const linked = linkedEvidenceForFinding(finding, evidenceItems)
    if (linked.length > 0) {
      lines.push('- **Evidence Vault citations:**')
      for (const item of linked) {
        const reference = item.reference ? `; reference: ${inline(item.reference)}` : ''
        lines.push(
          `  - \`${item.type}\` **${inline(item.title)}** — source: ${inline(item.source)}; captured: ${formatDateTime(item.timestamp)}${reference}`,
        )
        lines.push(`    - Note: ${inline(item.note)}`)
      }
    }
    lines.push('')
  })

  lines.push('---', `_Generated by NeonSec Academy — synthetic training exercise, ${formatDate(report.updatedAt)}._`)
  return lines.join('\n')
}
