import { useEffect, useRef, useState } from 'react'
import { useLocation } from 'react-router-dom'
import type { Finding, Report, Severity } from '../types'
import type { Lab } from '../data/labs'
import { useStore } from '../store/useStore'
import { uid } from '../lib/id'
import { formatDate } from '../lib/format'
import { PageHeader } from '../components/ui/PageHeader'
import { Panel } from '../components/ui/Panel'
import { EmptyState } from '../components/ui/EmptyState'

const SEVERITIES: Severity[] = ['critical', 'high', 'medium', 'low', 'info']
const SEV_CLASS: Record<Severity, string> = {
  critical: 'badge--red',
  high: 'badge--red',
  medium: 'badge--amber',
  low: 'badge--cyan',
  info: 'badge--purple',
}

function blankFinding(): Finding {
  return { id: uid('f-'), title: '', severity: 'medium', impact: '', remediation: '', evidence: '' }
}

function reportToMarkdown(r: Report): string {
  const lines = [`# ${r.title || 'Untitled Report'}`, '']
  if (r.scope) lines.push(`**Scope:** ${r.scope}`, '')
  lines.push('## Summary', '', r.summary || '_No summary._', '', '## Findings', '')
  if (r.findings.length === 0) lines.push('_No findings recorded._')
  r.findings.forEach((f, i) => {
    lines.push(`### ${i + 1}. [${f.severity.toUpperCase()}] ${f.title || 'Untitled finding'}`)
    lines.push(`- **Impact:** ${f.impact || '—'}`)
    lines.push(`- **Remediation:** ${f.remediation || '—'}`)
    if (f.evidence) lines.push(`- **Evidence:** ${f.evidence}`)
    lines.push('')
  })
  lines.push('---', `_Generated by NeonSec Academy — synthetic training exercise, ${formatDate(r.updatedAt)}._`)
  return lines.join('\n')
}

function download(name: string, text: string) {
  const blob = new Blob([text], { type: 'text/markdown' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = name
  a.click()
  URL.revokeObjectURL(url)
}

function reportFromLab(lab: Lab): Report {
  const now = Date.now()
  return {
    id: uid('r-'),
    title: `Report — ${lab.title}`,
    scope: `Synthetic lab: ${lab.category}. Allowed: ${lab.scope.allowed.join('; ')}.`,
    summary: lab.brief,
    findings: lab.modelFindings.map((f) => ({ id: uid('f-'), evidence: '', ...f })),
    createdAt: now,
    updatedAt: now,
  }
}

export function Reports() {
  const location = useLocation()
  const reports = useStore((s) => s.reports)
  const upsert = useStore((s) => s.upsertReport)
  const remove = useStore((s) => s.deleteReport)

  const [draft, setDraft] = useState<Report | null>(null)
  const [saved, setSaved] = useState(false)
  const seededRef = useRef(false)

  // seed from a lab hand-off
  useEffect(() => {
    if (seededRef.current) return
    seededRef.current = true
    const lab = (location.state as { prefillLab?: Lab } | null)?.prefillLab
    if (lab) {
      const r = reportFromLab(lab)
      upsert(r)
      setDraft(r)
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])

  const patch = (p: Partial<Report>) => {
    setDraft((d) => (d ? { ...d, ...p, updatedAt: Date.now() } : d))
    setSaved(false)
  }
  const patchFinding = (id: string, p: Partial<Finding>) =>
    setDraft((d) => (d ? { ...d, findings: d.findings.map((f) => (f.id === id ? { ...f, ...p } : f)), updatedAt: Date.now() } : d))

  const save = () => {
    if (!draft) return
    upsert(draft)
    setSaved(true)
  }

  // ---- editor ----
  if (draft) {
    return (
      <div className="page" style={{ maxWidth: 900 }}>
        <PageHeader
          eyebrow="Practical // Report Builder"
          title="Findings Report"
          actions={
            <>
              <button className="btn btn--ghost btn--sm" onClick={() => { save(); setDraft(null) }}>
                ← All reports
              </button>
              <button className="btn btn--primary btn--sm" onClick={save}>
                {saved ? '✓ Saved' : 'Save'}
              </button>
            </>
          }
        />

        <Panel className="mb-3">
          <div className="field">
            <label className="label">Title</label>
            <input className="input" value={draft.title} onChange={(e) => patch({ title: e.target.value })} />
          </div>
          <div className="field">
            <label className="label">Scope (synthetic)</label>
            <input className="input" value={draft.scope} onChange={(e) => patch({ scope: e.target.value })} placeholder="Synthetic dataset only…" />
          </div>
          <div className="field" style={{ margin: 0 }}>
            <label className="label">Executive summary</label>
            <textarea className="textarea" value={draft.summary} onChange={(e) => patch({ summary: e.target.value })} />
          </div>
        </Panel>

        <div className="row row--between mb-2">
          <h3 className="panel__title">Findings ({draft.findings.length})</h3>
          <button className="btn btn--ghost btn--sm" onClick={() => patch({ findings: [...draft.findings, blankFinding()] })}>
            ＋ Add finding
          </button>
        </div>

        <div className="stack mb-3">
          {draft.findings.map((f, i) => (
            <Panel key={f.id}>
              <div className="row row--between mb-2" style={{ gap: '0.5rem' }}>
                <span className={`badge ${SEV_CLASS[f.severity]}`}>#{i + 1} · {f.severity}</span>
                <button className="btn btn--danger btn--sm" onClick={() => patch({ findings: draft.findings.filter((x) => x.id !== f.id) })}>
                  ✕
                </button>
              </div>
              <div className="row wrap" style={{ gap: '0.6rem' }}>
                <div className="field grow" style={{ minWidth: 200 }}>
                  <label className="label">Title</label>
                  <input className="input" value={f.title} onChange={(e) => patchFinding(f.id, { title: e.target.value })} />
                </div>
                <div className="field" style={{ width: 140 }}>
                  <label className="label">Severity</label>
                  <select className="select" value={f.severity} onChange={(e) => patchFinding(f.id, { severity: e.target.value as Severity })}>
                    {SEVERITIES.map((s) => (
                      <option key={s} value={s}>
                        {s}
                      </option>
                    ))}
                  </select>
                </div>
              </div>
              <div className="field">
                <label className="label">Impact</label>
                <textarea className="textarea" style={{ minHeight: 52 }} value={f.impact} onChange={(e) => patchFinding(f.id, { impact: e.target.value })} />
              </div>
              <div className="field">
                <label className="label">Remediation</label>
                <textarea className="textarea" style={{ minHeight: 52 }} value={f.remediation} onChange={(e) => patchFinding(f.id, { remediation: e.target.value })} />
              </div>
              <div className="field" style={{ margin: 0 }}>
                <label className="label">Evidence (synthetic reference)</label>
                <input className="input" value={f.evidence} onChange={(e) => patchFinding(f.id, { evidence: e.target.value })} />
              </div>
            </Panel>
          ))}
          {draft.findings.length === 0 && <p className="muted t-sm">No findings yet — add one above.</p>}
        </div>

        <div className="row wrap" style={{ gap: '0.5rem' }}>
          <button className="btn btn--green" onClick={() => { save(); download(`${draft.title.replace(/\s+/g, '-').toLowerCase() || 'report'}.md`, reportToMarkdown(draft)) }}>
            ⤓ Export Markdown
          </button>
          <button
            className="btn btn--ghost"
            onClick={() => navigator.clipboard?.writeText(reportToMarkdown(draft))}
          >
            ⧉ Copy Markdown
          </button>
          <button className="btn btn--danger" onClick={() => { remove(draft.id); setDraft(null) }}>
            Delete report
          </button>
        </div>
      </div>
    )
  }

  // ---- list ----
  const newReport = () => {
    const now = Date.now()
    setDraft({ id: uid('r-'), title: '', scope: '', summary: '', findings: [], createdAt: now, updatedAt: now })
    setSaved(false)
  }

  return (
    <div className="page">
      <PageHeader
        eyebrow="Practical // Reports"
        title="Reports"
        sub="Practise the deliverable that actually matters on the job: clear findings with impact and remediation."
        actions={
          <button className="btn btn--primary btn--sm" onClick={newReport}>
            ＋ New report
          </button>
        }
      />

      {reports.length === 0 ? (
        <Panel>
          <EmptyState glyph="⎙" title="No reports yet" hint="Draft a report from any Safe Lab, or start a blank one. Export as Markdown when done.">
            <button className="btn btn--primary" onClick={newReport}>
              ＋ New report
            </button>
          </EmptyState>
        </Panel>
      ) : (
        <div className="stack stack--sm">
          {reports.map((r) => (
            <button key={r.id} className="neon-card" onClick={() => { setDraft(r); setSaved(true) }}>
              <div className="row row--between wrap" style={{ gap: '0.4rem' }}>
                <span className="display t-sm" style={{ color: 'var(--text-main)' }}>
                  {r.title || 'Untitled Report'}
                </span>
                <span className="term t-xs dim">{formatDate(r.updatedAt)}</span>
              </div>
              <div className="row wrap mt-1" style={{ gap: '0.3rem' }}>
                <span className="badge">{r.findings.length} findings</span>
                {r.findings.slice(0, 4).map((f) => (
                  <span key={f.id} className={`badge ${SEV_CLASS[f.severity]}`}>
                    {f.severity}
                  </span>
                ))}
              </div>
            </button>
          ))}
        </div>
      )}
    </div>
  )
}
